apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
spec:
  type: {{ .Values.type }}
  selector:
    app: {{ .Values.label }}
  ports:
    - protocol: {{ .Values.protocol }}
      port: {{ .Values.serviceport }}
      targetPort: {{ .Values.port }}
